{% set data = load_setup_py_data() %}

package:
  name: carla
  version: {{ data['version'] }}

source:
  path: ../PythonClient

build:
  noarch: python

requirements:
  build:
    - python >=3.5
    - setuptools

  host:
    - python >=3.5

  run:
    - python >=3.5

    - Pillow
    - numpy
    - protobuf
    - matplotlib
    - future

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
